# Generated by Django 5.0.14 on 2026-09-23 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(help_text='e.g. BIFPCL/IT/F/01', max_length=50, unique=True)),
                ('title', models.CharField(help_text='e.g. CCTV Troubleshooting Report & Checklist', max_length=255)),
                ('category', models.CharField(help_text='e.g. Surveillance, Network, Systems, Power', max_length=100)),
                ('revision', models.CharField(default='Rev: 00', max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('retention_period', models.CharField(default='3 Years', max_length=50)),
                ('icon', models.CharField(default='camera-video', help_text='Bootstrap icon name', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_fields_schema', models.JSONField(default=list, help_text="List of equipment fields: [{'key': 'camera_id', 'label': 'Camera ID / Name', 'placeholder': '...'}, {'key': 'location', 'label': 'Location'}]")),
                ('diagnostic_items_schema', models.JSONField(default=list, help_text="List of inspection checklist items: [{'id': 1, 'text': 'Correct camera ID and location confirmed'}]")),
                ('fault_options_schema', models.JSONField(default=list, help_text="List of fault classifications: [{'key': 'minor', 'label': '1. Minor issue corrected', 'desc': 'Loose power plug...'}]")),
                ('materials_enabled', models.BooleanField(default=True)),
                ('verification_items_schema', models.JSONField(default=list, help_text="List of verification items: ['Camera online and live view stable', 'Field of view acceptable']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
                'ordering': ['doc_no'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IT Team Member',
                'verbose_name_plural': 'IT Team Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('work_request_no', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('reported_by', models.CharField(blank=True, max_length=150)),
                ('contact_no', models.CharField(blank=True, max_length=100)),
                ('outage_reported_at', models.DateTimeField(blank=True, null=True)),
                ('site_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('total_downtime', models.CharField(blank=True, max_length=100)),
                ('equipment_data', models.JSONField(blank=True, default=dict)),
                ('diagnostics_data', models.JSONField(blank=True, default=dict)),
                ('fault_selected', models.CharField(blank=True, max_length=100)),
                ('action_taken_details', models.TextField(blank=True)),
                ('materials_data', models.JSONField(blank=True, default=list)),
                ('faulty_item_disposal', models.CharField(blank=True, max_length=100)),
                ('disposal_ref_no', models.CharField(blank=True, max_length=100)),
                ('warranty_status', models.CharField(blank=True, max_length=100)),
                ('vendor_po_ref', models.CharField(blank=True, max_length=100)),
                ('verification_checks', models.JSONField(blank=True, default=list)),
                ('final_status', models.CharField(default='Restored and Closed', max_length=100)),
                ('final_status_other', models.CharField(blank=True, max_length=150)),
                ('additional_findings', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted (Pending Supervisor Review)'), ('FORWARDED', 'Forwarded (Pending Final Approval)'), ('APPROVED', 'Approved (Finalized)'), ('RETURNED', 'Returned for Revision')], default='SUBMITTED', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('supervised_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checklists', to=settings.AUTH_USER_MODEL)),
                ('supervised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_checklists', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='checklists.checklisttemplate')),
                ('attended_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='checklists.teammember')),
            ],
            options={
                'verbose_name': 'Checklist Submission',
                'verbose_name_plural': 'Checklist Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
