# Generated by Django 5.0.14 on 2026-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistsubmission',
            name='attended_by',
        ),
        migrations.AddField(
            model_name='checklistsubmission',
            name='attended_by',
            field=models.ManyToManyField(related_name='submissions', to='checklists.teammember'),
        ),
    ]
