# Generated by Django 5.0.14 on 2026-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_remove_checklistsubmission_attended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsubmission',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
